# Generated by Django 2.1.5 on 2019-04-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='File_Size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
