# Generated by Django 2.1.5 on 2019-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_file_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File_Size',
            field=models.FloatField(),
        ),
    ]
