# Generated by Django 2.1.5 on 2019-04-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_file_lable'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Name', models.CharField(max_length=500)),
                ('Complain', models.IntegerField()),
                ('Recommend', models.IntegerField()),
                ('Query', models.IntegerField()),
                ('Appreciation', models.IntegerField()),
                ('Others', models.IntegerField()),
            ],
        ),
    ]
